version: "3"

vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: finance-tracker-web

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Install dependencies for both frontend and backend
  install:
    desc: Install dependencies for both frontend and backend
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: Install Go dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod download
      - echo "Backend dependencies installed"

  install:frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm install
      - echo "Frontend dependencies installed"

  # Development mode - run both frontend and backend
  dev:
    desc: Run both frontend and backend in development mode
    cmds:
      - task services:up
      - task --parallel dev:backend dev:frontend

  dev:backend:
    desc: Run backend in development mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.dev air
    interrupt: true

  dev:frontend:
    desc: Run Angular development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm start
    interrupt: true

  # Production mode - run both frontend and backend
  prod:
    desc: Run both frontend and backend in production mode
    cmds:
      - task: prod:backend
      - task: prod:frontend

  prod:backend:
    desc: Run backend in production mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.prod go run ./cmd/backend/*.go
    interrupt: true

  prod:frontend:
    desc: Run frontend in production mode (build + preview)
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build
      - pnpm preview
    interrupt: true

  # Individual tasks for running separately
  backend:dev:
    desc: Run only backend in development mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.dev air
    interrupt: true

  backend:prod:
    desc: Run only backend in production mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.prod go run ./cmd/backend/*.go
    interrupt: true

  frontend:dev:
    desc: Run only Angular development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm start
    interrupt: true

  frontend:prod:
    desc: Build and preview frontend for production
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build
      - pnpm preview
    interrupt: true

  services:up:
    desc: Ensure local infrastructure containers are running
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - |
        set -euo pipefail

        ensure_container() {
          local name="$1"
          local service="$2"

          if docker ps -a --format '{{.Names}}' | grep -w "$name" >/dev/null 2>&1; then
            if docker ps --filter "name=$name" --filter "status=running" --format '{{.Names}}' | grep -w "$name" >/dev/null 2>&1; then
              echo "Container $name already running"
            else
              echo "Starting existing container $name"
              docker start "$name" >/dev/null
            fi
          else
            echo "Creating container $name using docker compose service $service"
            docker compose -f dev.docker-compose.yml up -d "$service"
          fi
        }

        ensure_container "finance-tracker-postgres" "postgres"
        ensure_container "finance-tracker-redis" "redis"

  docs:generate:
    desc: Generate Swagger documentation and update frontend API types
    cmds:
      - task: docs:generate:backend
      - task: docs:generate:frontend

  docs:generate:backend:
    desc: Generate Swagger documentation from annotations
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - swag init -g cmd/backend/main.go -o internal/docs --parseDependency --parseInternal
      - echo "Swagger docs generated successfully"

  docs:generate:frontend:
    desc: Generate TypeScript API types from Swagger docs
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm run generate:api
      - echo "Frontend API types generated successfully"
