version: "3"

vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: finance-tracker-web

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Install dependencies for both frontend and backend
  install:
    desc: Install dependencies for both frontend and backend
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: Install Go dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod download
      - echo "Backend dependencies installed"

  install:frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm install
      - echo "Frontend dependencies installed"

  # Development mode - run both frontend and backend
  dev:
    desc: Run both frontend and backend in development mode
    cmds:
      - task services:up
      - task --parallel dev:backend dev:frontend

  dev:backend:
    desc: Run backend in development mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.dev air
    interrupt: true

  dev:frontend:
    desc: Run Next.js development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm dev
    interrupt: true

  # Production mode - run both frontend and backend
  prod:
    desc: Run both frontend and backend in production mode
    cmds:
      - task: prod:backend
      - task: prod:frontend

  prod:backend:
    desc: Run backend in production mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.prod go run ./cmd/backend/*.go
    interrupt: true

  prod:frontend:
    desc: Run frontend in production mode (build + start)
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build
      - pnpm start
    interrupt: true

  # Individual tasks for running separately
  backend:dev:
    desc: Run only backend in development mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.dev air
    interrupt: true

  backend:prod:
    desc: Run only backend in production mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - ENV_FILE=.env.prod go run ./cmd/backend/*.go
    interrupt: true

  frontend:dev:
    desc: Run only Next.js development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm dev
    interrupt: true

  frontend:prod:
    desc: Build and start frontend for production
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build
      - pnpm start
    interrupt: true

  frontend:build:
    desc: Build Next.js application for production
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build
      - echo "Next.js build completed successfully"

  frontend:lint:
    desc: Lint Next.js application using Biome
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm lint

  frontend:format:
    desc: Format Next.js code using Biome
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm format
      - echo "Code formatted successfully"

  services:up:
    desc: Ensure local infrastructure containers are running
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - |
        set -euo pipefail

        ensure_container() {
          local name="$1"
          local service="$2"

          if docker ps -a --format '{{.Names}}' | grep -w "$name" >/dev/null 2>&1; then
            if docker ps --filter "name=$name" --filter "status=running" --format '{{.Names}}' | grep -w "$name" >/dev/null 2>&1; then
              echo "Container $name already running"
            else
              echo "Starting existing container $name"
              docker start "$name" >/dev/null
            fi
          else
            echo "Creating container $name using docker compose service $service"
            docker compose -f dev.docker-compose.yml up -d "$service"
          fi
        }

        ensure_container "finance-tracker-postgres" "postgres"
        ensure_container "finance-tracker-redis" "redis"

  docs:generate:
    desc: Generate Swagger documentation and update frontend API types
    cmds:
      - task: docs:generate:backend
      - task: docs:generate:frontend

  docs:generate:backend:
    desc: Generate Swagger documentation from annotations
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - swag init -g cmd/backend/main.go -o internal/docs --parseDependency --parseInternal --parseDepth 2
      - echo "Swagger docs generated successfully"

  docs:generate:frontend:
    desc: Generate TypeScript API types from Swagger docs
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm run generate:api
      - echo "Frontend API types generated successfully"

  # Next.js specific tasks
  frontend:type-check:
    desc: Type check Next.js TypeScript files
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm exec tsc --noEmit
      - echo "Type check passed successfully"

  frontend:clean:
    desc: Clean Next.js build artifacts and cache
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - rm -rf .next
      - rm -rf node_modules/.cache
      - echo "Next.js cache cleaned successfully"

  # Combined tasks
  lint:
    desc: Lint both backend and frontend
    cmds:
      - task: frontend:lint
      - echo "Linting completed"

  format:
    desc: Format both backend and frontend code
    cmds:
      - task: frontend:format
      - echo "Formatting completed"

  type-check:
    desc: Type check frontend and verify backend
    cmds:
      - task: frontend:type-check
      - echo "Type checking completed"

  clean:
    desc: Clean build artifacts for both frontend and backend
    cmds:
      - task: frontend:clean
      - echo "Cleanup completed"

  # Husky and Git hooks
  husky:install:
    desc: Install and setup Husky git hooks
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm install
      - pnpm prepare
      - echo "Husky installed and configured successfully"

  husky:test:
    desc: Test Husky hooks without committing
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "Testing pre-commit hook..."
      - pnpm lint-staged
      - echo "Pre-commit hook test passed!"

  git:commit:
    desc: Helper to show what Husky will check before commit
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "Husky will run on commit:"
      - echo "  - lint-staged (Biome lint & format)"
      - echo ""
      - echo "Husky will run on push:"
      - echo "  - Type checking"
      - echo "  - Linting"
