/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternalDomainAccountBank } from './internalDomainAccountBank';


export interface InternalDomainAccountAccount { 
    account_name?: string;
    account_number?: string;
    account_type?: string;
    bank?: InternalDomainAccountBank;
    bank_id?: string;
    current_balence?: number;
    id?: string;
    user_id?: string;
}

