/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalDomainAccountUpdateAccountReq { 
    account_id: string;
    account_name?: string;
    account_number?: string;
    account_type?: string;
    bank_id?: string;
    current_balence?: number;
    is_primary?: boolean;
}

