/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalDomainAccountBank { 
    code?: string;
    created_at?: string;
    id?: string;
    is_active?: boolean;
    name?: string;
    updated_at?: string;
}

