/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalDomainAuthGetAuthUserResponse { 
    created_at?: string;
    database_url?: string;
    email?: string;
    is_active?: boolean;
    lifetime_expense?: number;
    lifetime_income?: number;
    llm_parse_credits?: number;
    updated_at?: string;
    use_llm_parsing?: boolean;
}

