/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalDomainUserUser { 
    clerk_id?: string;
    created_at?: string;
    database_url?: string;
    email?: string;
    is_active?: boolean;
    lifetime_expense?: number;
    lifetime_income?: number;
    updated_at?: string;
    user_llm_parsing?: boolean;
}

