/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalDomainAccountCreateAccountReq { 
    account_name: string;
    account_number: number;
    account_type: string;
    bank_id: string;
}

