/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternalDomainSystemHealthCheckResult } from './internalDomainSystemHealthCheckResult';


export interface InternalDomainSystemHealthResponse { 
    checks?: { [key: string]: InternalDomainSystemHealthCheckResult; };
    environment?: string;
    status?: string;
    timestamp?: string;
}

