/**
 * Finance Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalDomainUserUpdateUserReq { 
    database_url?: string;
    lifetime_expense?: number;
    lifetime_income?: number;
    use_llm_parsing?: boolean;
}

