// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/user": {
            "get": {
                "description": "Returns the current authenticated user's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_domain_auth.GetAuthUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns health information about infrastructure dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_domain_system.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_domain_system.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_domain_auth.GetAuthUserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-02T15:04:05Z"
                },
                "database_url": {
                    "type": "string",
                    "example": "postgresql://user:pass@localhost/db"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "lifetime_expense": {
                    "type": "number",
                    "example": 30000
                },
                "lifetime_income": {
                    "type": "number",
                    "example": 50000
                },
                "llm_parse_credits": {
                    "type": "integer",
                    "example": 100
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-02T15:04:05Z"
                },
                "use_llm_parsing": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_domain_system.HealthCheckResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "connection refused"
                },
                "response_time": {
                    "type": "string",
                    "example": "5ms"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "internal_domain_system.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/internal_domain_system.HealthCheckResult"
                    }
                },
                "environment": {
                    "type": "string",
                    "example": "production"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-01-02T15:04:05Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
